"""Tests for deterministic docs refresh-llm command surface autogen."""

from __future__ import annotations

import hashlib
import json
from typing import TYPE_CHECKING

from typer.testing import CliRunner

from taskx.cli import cli
from taskx.docs.refresh_llm import (
    AUTOGEN_END,
    AUTOGEN_START,
    apply_autogen_update,
    refresh_llm_docs,
    render_autogen_block,
)

if TYPE_CHECKING:
    from pathlib import Path


RUNNER = CliRunner()


def _write_target_files(repo_root: Path, *, include_codex_markers: bool = True) -> None:
    (repo_root / "AGENTS.md").write_text(
        f"# AGENTS\n\n{AUTOGEN_START}\nold\n{AUTOGEN_END}\n",
        encoding="utf-8",
    )
    (repo_root / "CLAUDE.md").write_text(
        f"# CLAUDE\n\n{AUTOGEN_START}\nold\n{AUTOGEN_END}\n",
        encoding="utf-8",
    )

    if include_codex_markers:
        codex_text = f"# CODEX\n\n{AUTOGEN_START}\nold\n{AUTOGEN_END}\n"
    else:
        codex_text = "# CODEX\n\nNo markers yet.\n"
    (repo_root / "CODEX.md").write_text(codex_text, encoding="utf-8")


def test_determinism_identical_hash_for_identical_inputs(tmp_path: Path) -> None:
    repo_root = tmp_path / "repo"
    repo_root.mkdir(parents=True, exist_ok=True)
    _write_target_files(repo_root)

    first = refresh_llm_docs(repo_root=repo_root, cli_app=cli, check=False)
    second = refresh_llm_docs(repo_root=repo_root, cli_app=cli, check=False)

    assert first.command_surface_hash == second.command_surface_hash
    expected_hash = hashlib.sha256(first.block_content.encode("utf-8")).hexdigest()
    assert first.command_surface_hash == expected_hash


def test_idempotency_second_run_has_no_changes(tmp_path: Path) -> None:
    repo_root = tmp_path / "repo"
    repo_root.mkdir(parents=True, exist_ok=True)
    _write_target_files(repo_root)

    first = refresh_llm_docs(repo_root=repo_root, cli_app=cli, check=False)
    assert first.modified or first.created

    second = refresh_llm_docs(repo_root=repo_root, cli_app=cli, check=False)
    assert second.created == ()
    assert second.modified == ()


def test_refusal_on_invalid_marker_structure_cli_exit_2(tmp_path: Path, monkeypatch) -> None:
    repo_root = tmp_path / "repo"
    repo_root.mkdir(parents=True, exist_ok=True)

    (repo_root / "AGENTS.md").write_text(f"# AGENTS\n{AUTOGEN_START}\n", encoding="utf-8")
    (repo_root / "CLAUDE.md").write_text(f"# CLAUDE\n{AUTOGEN_START}\nold\n{AUTOGEN_END}\n", encoding="utf-8")
    (repo_root / "CODEX.md").write_text(f"# CODEX\n{AUTOGEN_START}\nold\n{AUTOGEN_END}\n", encoding="utf-8")

    monkeypatch.chdir(repo_root)
    result = RUNNER.invoke(cli, ["docs", "refresh-llm", "--repo-root", str(repo_root)])
    assert result.exit_code == 2
    assert "Invalid AUTOGEN marker structure" in result.stdout


def test_codex_marker_insertion_when_missing(tmp_path: Path) -> None:
    repo_root = tmp_path / "repo"
    repo_root.mkdir(parents=True, exist_ok=True)
    _write_target_files(repo_root, include_codex_markers=False)

    refresh_llm_docs(repo_root=repo_root, cli_app=cli, check=False)
    codex = (repo_root / "CODEX.md").read_text(encoding="utf-8")
    assert codex.count(AUTOGEN_START) == 1
    assert codex.count(AUTOGEN_END) == 1

    refresh_llm_docs(repo_root=repo_root, cli_app=cli, check=False)
    codex_again = (repo_root / "CODEX.md").read_text(encoding="utf-8")
    assert codex_again.count(AUTOGEN_START) == 1
    assert codex_again.count(AUTOGEN_END) == 1


def test_check_mode_exits_one_on_drift(tmp_path: Path, monkeypatch) -> None:
    repo_root = tmp_path / "repo"
    repo_root.mkdir(parents=True, exist_ok=True)
    _write_target_files(repo_root)

    monkeypatch.chdir(repo_root)
    result = RUNNER.invoke(cli, ["docs", "refresh-llm", "--repo-root", str(repo_root), "--check"])
    assert result.exit_code == 1

    report_json = repo_root / "out" / "taskx_docs_refresh_llm" / "DOCS_REFRESH_LLM_REPORT.json"
    payload = json.loads(report_json.read_text(encoding="utf-8"))
    assert payload["check_mode"] is True
    assert payload["modified"]


def test_rendered_block_format_and_sorting() -> None:
    surface = {
        "top_level": ["b", "a"],
        "groups": {"route": ["plan", "handoff"], "docs": ["refresh-llm"]},
    }
    block = render_autogen_block(surface)
    assert "## TaskX Command Surface (Autogenerated)" in block
    assert "Generated by: taskx docs refresh-llm" in block


def test_apply_update_preserves_outside_text() -> None:
    before = (
        "prefix\n"
        f"{AUTOGEN_START}\n"
        "old\n"
        f"{AUTOGEN_END}\n"
        "suffix\n"
    )
    block = "## TaskX Command Surface (Autogenerated)"
    after, state = apply_autogen_update(before, block)

    assert state == "modified"
    assert after.startswith("prefix\n")
    assert after.endswith("suffix\n")
